# Calibrate camera colors

In [1]:
import camera_tools as ct
import numpy as np

The following will open three windows. Adjust the sliders in the "Trackbars window until only the Lego pieces are white. We are using the "LAB" color space. The "L" sliders are for luminosity, so keep these close to 0 and 255 respectively. The "A" and "B" sliders are for color components. Find the range that corresponds to green for your specific camera. When you're done, press the "ESC" key, and the function will return the values.

In [3]:
low_green, high_green = ct.colorpicker()
print(low_green)
print(high_green)

QFontDatabase: Cannot find font directory /home/arian-sumak/miniconda3/envs/biocontrol/lib/python3.9/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/arian-sumak/miniconda3/envs/biocontrol/lib/python3.9/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/arian-sumak/miniconda3/envs/biocontrol/lib/python3.9/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/arian-sumak/miniconda3/envs/biocontrol/lib/python3.9/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to 

[  0  76 145]
[179 140 171]


Test to see how the new values work:

In [ ]:
low_green = np.array([41, 84, 0], dtype=np.uint8)
high_green = np.array([99, 117, 143], dtype=np.uint8)


#[61 35  0]
#[253 162 121] blue

#[  0  76 145]
#[179 140 171] yellow

cam = ct.prepare_camera()

ct.show_camera(cam, low_green, high_green)